name: Time to move
description: Move it from one place to another
labels: the-move
title: Request to move <replace-with-shop-url> to Canada
body:
  - type: markdown
    attributes:
      value: "## Moving is not easy!"
  - type: input
    attributes:
      label: The ID
      description: This is where the ID goes
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: This is approved?
      description: Has this actually been approved?
      options:
        - label: Yes!
          required: true
